version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    user: "root"
    volumes:
      - ./start.sh:/start.sh
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    user: "root"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./acme-challenge:/var/www/html/.well-known/acme-challenge
      - ./certified_ssl:/etc/nginx/ssl
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app

  certbot:
    image: certbot/certbot
    user: "root"
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./acme-challenge:/var/www/html/.well-known/acme-challenge
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 86400; done;'"
